### PR TITLE
Its SEIZURE TIME

### PR DESCRIPTION
**Pull request by DrBeta**

### CODE REVIEW

**Comment by DrBeta** [comment]
I think that the idea of the yolo page is very interesting @thesephist

**Comment by DrBeta** [comment]
@thesephist is there a reason that you have accepted everyone else's PRs but not mine?

**Comment by DrBeta** [comment]
@thesephist is there any reason you have accepted everyone else's PR but not mine?

**Comment by thesephist** [comment]
Hey, sorry @DrBeta — as much as I want this thing to be a free-for-all, I'm gonna make an executive decision to say no against the changing background and autoplay audio for reasons of

- It's super annoying (which I know is the point, but still) and
- Has potential accessibility issues

Also, the autoplay won't work in most browsers because browsers block such things to not be annoying.

If you want to make less.... I guess, seizure-inducing / non-annoying changes to the site, I'd be happy to accept. I hate to be a party pooper but previous experiences with other changes like this to this page taught me there have to be limits :(

**Pull request closed without merging**
